<?php
// don't load directly
if ( ! defined( 'ABSPATH' ) ) exit;

$sengine = array(
	array('u'=>'google.', 'q'=>'q'),
	array('u'=>'bing.', 'q'=>'q'),
	array('u'=>'search.live.com', 'q'=>'q'),
	array('u'=>'seznam.cz', 'q'=>'q'),
	array('u'=>'filestube.com', 'q'=>'q'),
	array('u'=>'searchfunmoods.com', 'q'=>'q'),
	array('u'=>'k9safesearch.com', 'q'=>'q'),
	array('u'=>'searchmobileonline.com', 'q'=>'q'),
	array('u'=>'peeplo.dk', 'q'=>'q'),
	array('u'=>'peeplo.com', 'q'=>'q'),
	array('u'=>'search.certified-toolbar.com', 'q'=>'q'),
	array('u'=>'searchamong.com', 'q'=>'query'),
	array('u'=>'isearch.alot.com', 'q'=>'q'),
	array('u'=>'search.alot.com', 'q'=>'q'),
	array('u'=>'search.zonealarm.com', 'q'=>'q'),
	array('u'=>'isearch.avg.com', 'q'=>'q'),
	array('u'=>'search.avg.com', 'q'=>'q'),
	array('u'=>'60searchengines.com', 'q'=>'q'),
	array('u'=>'search.yippy.', 'q'=>'query'),
	array('u'=>'video.google.', 'q'=>'q'),
	array('u'=>'alltheweb.com', 'q'=>'q'),
	array('u'=>'ask.', 'q'=>'q'),
	array('u'=>'looksmart.', 'q'=>'qt'),
	array('u'=>'altavista.de', 'q'=>'q'),
	array('u'=>'altavista.com', 'q'=>'q'),
	array('u'=>'web.de', 'q'=>'su'),
	array('u'=>'fireball.de', 'q'=>'query'),
	array('u'=>'lycos.de', 'q'=>'query'),
	array('u'=>'lycos.com', 'q'=>'query'),
	array('u'=>'dogpile.com', 'q'=>'q'),
	array('u'=>'aol.com', 'q'=>'query'),
	array('u'=>'aol.com', 'q'=>'q'),
	array('u'=>'talktalk.co.uk', 'q'=>'query'),
	array('u'=>'best-price.com', 'q'=>'query'),
	array('u'=>'googleusercontent.com', 'q'=>'q'),
	array('u'=>'ask.com', 'q'=>'q'),
	array('u'=>'search.conduit.com', 'q'=>'q'),
	array('u'=>'jauhari.net/', 'q'=>'search'),
	array('u'=>'search.iminent.com', 'q'=>'q'),
	array('u'=>'search.incredibar.com', 'q'=>'q'),
	array('u'=>'search.sweetim.com', 'q'=>'q'),
	array('u'=>'search.daum.net', 'q'=>'q'),
	array('u'=>'search.b1.org', 'q'=>'q'),
	array('u'=>'taringa.net', 'q'=>'q'),
	array('u'=>'mysearchresults.com', 'q'=>'q'),
	array('u'=>'search.snap.do', 'q'=>'q'),
	array('u'=>'ricerca.virgilio.it', 'q'=>'qs'),
	array('u'=>'searchya.com', 'q'=>'q'),
	array('u'=>'4-shared.eu', 'q'=>'q'),
	array('u'=>'runber.com', 'q'=>'q'),
	array('u'=>'claro-search.com', 'q'=>'q'),
	array('u'=>'univision.com', 'q'=>'query'),
	array('u'=>'fastaddressbar.com', 'q'=>'s'),
	array('u'=>'delta-search.com', 'q'=>'q'),
	array('u'=>'blekko.com', 'q'=>'q'),
	array('u'=>'start.funmoods.com', 'q'=>'q'),
	array('u'=>'search.icq.com', 'q'=>'q'),
	array('u'=>'search.v9.com', 'q'=>'q'),
	array('u'=>'search.softonic.com', 'q'=>'q'),
	array('u'=>'search.comcast.net', 'q'=>'q'),
	array('u'=>'find.tdc.dk', 'q'=>'q'),
	array('u'=>'m.tdc.dk', 'q'=>'googleq'),
	array('u'=>'aolsearch.com', 'q'=>'q'),
	array('u'=>'kvasir.no', 'q'=>'q'),
	array('u'=>'lycos.com', 'q'=>'q'),
	array('u'=>'jubii.dk', 'q'=>'q'),
	array('u'=>'genieo.com', 'q'=>'q'),
	array('u'=>'incredimail.com', 'q'=>'q'),
	array('u'=>'chatzum.com', 'q'=>'q'),
	array('u'=>'nova.rambler.ru', 'q'=>'query'),
	array('u'=>'yahoo.', 'q'=>'p'),
	array('u'=>'myhealthcare.com', 'q'=>'q'),
	array('u'=>'search.mywebsearch.com', 'q'=>'searchfor'),
	array('u'=>'search.creativetoolbars.com', 'q'=>'q'),
	array('u'=>'plusnetwork.com', 'q'=>'q'),
	array('u'=>'maps.google.com', 'q'=>'q'),
	array('u'=>'startsiden.no', 'q'=>'q'),
	array('u'=>'29searchengines.com', 'q'=>'q'),
	array('u'=>'30searchengines.com', 'q'=>'q'),
	array('u'=>'90searchengines.com', 'q'=>'q'),
	array('u'=>'buscador.terra.com', 'q'=>'query'),
	array('u'=>'map.krak.dk', 'q'=>'search_word'),
	array('u'=>'firma.eniro.dk', 'q'=>'search_word'),
	array('u'=>'eniro.dk', 'q'=>'search_word'),
	array('u'=>'search.speedfox.me', 'q'=>'q'),
	array('u'=>'baidu.com', 'q'=>'wd'),
	array('u'=>'hotbot.com', 'q'=>'q'),
	array('u'=>'about.com', 'q'=>'q'),
	array('u'=>'www1.dlinksearch.com', 'q'=>'q'),
	array('u'=>'search.eazel.com', 'q'=>'q'),
	array('u'=>'en.eazel.com', 'q'=>'q'),
	array('u'=>'valentine.com', 'q'=>'q'),
	array('u'=>'search.centrum.cz', 'q'=>'q'),
	array('u'=>'isesfeel.com', 'q'=>'title'),
	array('u'=>'busca.starmedia.com', 'q'=>'buscar'),
	array('u'=>'clikseguro.com', 'q'=>'q'),
	array('u'=>'elcoblogs.com', 'q'=>'search'),
	array('u'=>'tmob.search-help.com', 'q'=>'search'),
	array('u'=>'es.luna.tv', 'q'=>'q'),
	array('u'=>'startpins.com', 'q'=>'q'),
	array('u'=>'buzzdock.com', 'q'=>'q'),
	array('u'=>'amazon.com', 'q'=>'query'),
	array('u'=>'amazon.es', 'q'=>'query'),
	array('u'=>'amazon.fr', 'q'=>'query'),
	array('u'=>'buscador.terra.cl', 'q'=>'query'),
	array('u'=>'buscador.terra.es', 'q'=>'query'),
	array('u'=>'buscar.terra.com.ar', 'q'=>'query'),
	array('u'=>'river4dwn.com', 'q'=>'title'),
	array('u'=>'infospace.com', 'q'=>'q'),
	array('u'=>'amazon.es', 'q'=>'query'),
	array('u'=>'start.toshiba.com', 'q'=>'q'),
	array('u'=>'webcrawler.de', 'q'=>'q'),
	array('u'=>'webcrawler.com', 'q'=>'q'),
	array('u'=>'metacrawler.com', 'q'=>'q'),
	array('u'=>'start.facemoods.com', 'q'=>'q'),
	array('u'=>'excite.com', 'q'=>'q'),
	array('u'=>'search.monstercrawler.com', 'q'=>'q'),
	array('u'=>'search.ereadingsource.com', 'q'=>'q'),
	array('u'=>'search.smilebox.com', 'q'=>'q'),
	array('u'=>'home.gamesgofree.com', 'q'=>'s'),
	array('u'=>'find-and-go.com', 'q'=>'q'),
	array('u'=>'inbox.com', 'q'=>'q'),
	array('u'=>'search.searchcompletion.com', 'q'=>'q'),
	array('u'=>'startgoogle.startpagina.nl', 'q'=>'q'),
	array('u'=>'wow.com', 'q'=>'q'),
	array('u'=>'search.earthlink.net', 'q'=>'q'),
	array('u'=>'statmyweb.com', 'q'=>'q'),
	array('u'=>'search.smartaddressbar.com', 'q'=>'s'),
	array('u'=>'go.mail.ru', 'q'=>'q'),
	array('u'=>'search.atajitos.com', 'q'=>'q'),
	array('u'=>'arianna.libero.it', 'q'=>'query'),
	array('u'=>'govome.com', 'q'=>'q'),
	array('u'=>'gooofullsearch.com', 'q'=>'q'),
	array('u'=>'static.flipora.com', 'q'=>'q'),
	array('u'=>'home.myplaycity.com', 'q'=>'s'),
	array('u'=>'searchcanvas.com', 'q'=>'q'),
	array('u'=>'tmob.search-help.net', 'q'=>'search'),
	array('u'=>'buscar.hispavista.com', 'q'=>'q'),
	array('u'=>'search.snapdo.com', 'q'=>'q'),
	array('u'=>'search.carrot2.org', 'q'=>'query'),
	array('u'=>'ya.03compu.ru', 'q'=>'query'),
	array('u'=>'tuvaro.com', 'q'=>'q'),
	array('u'=>'handycafe.com', 'q'=>'q'),
	array('u'=>'netzero.net', 'q'=>'query'),
	array('u'=>'globososo.com', 'q'=>'q'),
	array('u'=>'quebles.com', 'q'=>'q'),
	array('u'=>'search-results.com', 'q'=>'q'),
	array('u'=>'start.funmoods.com', 'q'=>'q'),
	array('u'=>'babylon.com', 'q'=>'q'),
	array('u'=>'search.comcast.net', 'q'=>'q'),
	array('u'=>'search.pch.com', 'q'=>'q'),
	array('u'=>'infospace.com', 'q'=>'q'),
	array('u'=>'search.atajositios.com', 'q'=>'q'),
	array('u'=>'search.ultrasurf.us', 'q'=>'q'),
	array('u'=>'ittravel.info', 'q'=>'q'),
	array('u'=>'search.fbdownloader.com', 'q'=>'q'),
	array('u'=>'search.peoplepc.com', 'q'=>'q'),
	array('u'=>'cc.bingj.com', 'q'=>'q'),
	array('u'=>'holasearch.com', 'q'=>'q'),
	array('u'=>'newsatdaynet.info', 'q'=>'q'),
	array('u'=>'univision.com', 'q'=>'q'),
	array('u'=>'websearch.com', 'q'=>'q'),
	array('u'=>'bgoog.com', 'q'=>'q'),
	array('u'=>'search.domainnotfound.optimum.net', 'q'=>'q'),
	array('u'=>'busca.uol.com.br', 'q'=>'q'),
	array('u'=>'100searchengines.com', 'q'=>'q'),
	array('u'=>'alhea.com', 'q'=>'q'),
	array('u'=>'finddotcom.com', 'q'=>'text'),
	array('u'=>'find1friend.com', 'q'=>'q'),
	array('u'=>'search.qone8.com', 'q'=>'q'),
	array('u'=>'alhea.com', 'q'=>'q'),
	array('u'=>'start.myplaycity.com', 'q'=>'s'),
	array('u'=>'search.nation.com', 'q'=>'q'),
	array('u'=>'findhurtig.dk', 'q'=>'q'),
	array('u'=>'websearchinc.net', 'q'=>'query'),
	array('u'=>'valentine.com', 'q'=>'q'),
	array('u'=>'overskrift.dk', 'q'=>'q'),
	array('u'=>'info.com', 'q'=>'qkw'),
	array('u'=>'mysearchdial.com', 'q'=>'q'),
	array('u'=>'mysearchdial.com', 'q'=>'q'),
	array('u'=>'search.whitesmoke.com', 'q'=>'q'),
	array('u'=>'suche.aol.de', 'q'=>'q'),
	array('u'=>'duckduckgo.com', 'q'=>'q'),
	array('u'=>'mysearchdial.com', 'q'=>'q'),
	array('u'=>'serp.flipora.com', 'q'=>'q'),
	array('u'=>'search.fluxbee.com', 'q'=>'q'),
	array('u'=>'search.imesh.com', 'q'=>'q'),
	array('u'=>'naver.com', 'q'=>'query'),
	array('u'=>'msn.com', 'q'=>'q'),
	array('u'=>'cnn.com', 'q'=>'query'),
	array('u'=>'voila.fr', 'q'=>'kw'),
	array('u'=>'alice.com', 'q'=>'query'),
	array('u'=>'wp.pl', 'q'=>'q'),
	array('u'=>'mynet.com', 'q'=>'query'),
	array('u'=>'thiv.net', 'q'=>'q'),
	array('u'=>'yam.net', 'q'=>'k'),
	array('u'=>'ecosia.org', 'q'=>'q'),
	array('u'=>'safehomepage.com', 'q'=>'q'),
	array('u'=>'zapmeta.dk', 'q'=>'q'),
	array('u'=>'suche.t-online.de', 'q'=>'q'),
	array('u'=>'degulesider.dk', 'q'=>'search_word'),
	array('u'=>'search.bt.com', 'q'=>'p'),
	array('u'=>'search.webssearches.com', 'q'=>'q'),
	array('u'=>'nootrino.com', 'q'=>'q'),
	array('u'=>'opskrifter.dseneste.dk', 'q'=>'opskrift'),
	array('u'=>'lasaoren.com', 'q'=>'q'),
	array('u'=>'cocorico.com', 'q'=>'s'),
	array('u'=>'indexa.fr', 'q'=>'chaine'),
	array('u'=>'sharelook.fr', 'q'=>'keyword'),
	array('u'=>'lemoteur.ke.voila.fr', 'q'=>'kw'),
	array('u'=>'astromenda.com', 'q'=>'q'),
	array('u'=>'soeg.jubii.dk', 'q'=>'q'),
	array('u'=>'speedial.com', 'q'=>'q'),
	array('u'=>'foodgawker.com', 'q'=>'s'),
	array('u'=>'searches.vi-view.com', 'q'=>'q'),
	array('u'=>'buenosearch.com', 'q'=>'q'),
	array('u'=>'search-results.mobi', 'q'=>'q'),
	array('u'=>'dba.dk', 'q'=>'soeg'),
	array('u'=>'sweetpacks-search.com', 'q'=>'soeg'),
	array('u'=>'searchgol.com', 'q'=>'q'),
	array('u'=>'webfetch.co.uk', 'q'=>'q'),
	array('u'=>'inspsearch.com', 'q'=>'q'),
	array('u'=>'search.gboxapp.com', 'q'=>'q'),
	array('u'=>'sprintpcs.com', 'q'=>'q'),
	array('u'=>'avantbrowser.com', 'q'=>'q'),
	array('u'=>'golsearch.com', 'q'=>'q'),
	array('u'=>'crawler.com', 'q'=>'q'),
	array('u'=>'43searchengines.com', 'q'=>'q'),
	array('u'=>'searches.qone8.com', 'q'=>'q'),
	array('u'=>'zapmeta.mx', 'q'=>'q'),
	array('u'=>'findwide.com', 'q'=>'k'),
	array('u'=>'virgilio.it', 'q'=>'qrs'),
	array('u'=>'quick-seeker.com', 'q'=>'q'),
	array('u'=>'esmuy.co', 'q'=>'query'),
	array('u'=>'sear4m.xyz', 'q'=>'q'),
	array('u'=>'googleweblight.com', 'q'=>'q'),
	array('u'=>'sear4m.xyz', 'q'=>'q'),
	array('u'=>'search.smartshopping.com', 'q'=>'keywords'),
	array('u'=>'mysearch.com', 'q'=>'q'),
	array('u'=>'baserad.xyz', 'q'=>'q'),
	array('u'=>'parverts.xyz', 'q'=>'q'),
	array('u'=>'wowstart.online', 'q'=>'q'),
	array('u'=>'search2016.space', 'q'=>'q'),
	array('u'=>'msearch.xyz', 'q'=>'q'),
	array('u'=>'bestsearch.space', 'q'=>'q'),
	array('u'=>'windowssearch.com', 'q'=>'q'),
	array('u'=>'internationalnewsportal.com', 'q'=>'q'),
	array('u'=>'monsear.xyz', 'q'=>'q'),
	array('u'=>'parallaxsearch.com', 'q'=>'qs'),
	array('u'=>'newpage16.site', 'q'=>'q'),
	array('u'=>'ustarts.xyz', 'q'=>'q'),
	array('u'=>'allsearch.space', 'q'=>'q'),
	array('u'=>'gosearches.online', 'q'=>'q'),
	array('u'=>'maindom.xyz', 'q'=>'q'),
	array('u'=>'xsearch.space', 'q'=>'q'),
	array('u'=>'dealwifi.com', 'q'=>'q'),
	array('u'=>'search.mail.com', 'q'=>'q'),
	array('u'=>'legetoj-dk.com', 'q'=>'s'),
	array('u'=>'kvikstart.dk', 'q'=>'q'),
	array('u'=>'com.google.android.googlequicksearchbox', 'q'=>'s'),
	array('u'=>'localmoxie.com', 'q'=>'keyword'),
	array('u'=>'lenovo.com', 'q'=>'q'),
	array('u'=>'gigablast.com', 'q'=>'q'),
	array('u'=>'mamma.com', 'q'=>'q'),
	array('u'=>'faroo.com', 'q'=>'q'),
	array('u'=>'dmoz.org', 'q'=>'q'),
	array('u'=>'esmuy.es', 'q'=>'query'),
	array('u'=>'qwant.com', 'q'=>'q'),
	array('u'=>'start.fyi', 'q'=>'q'),
	array('u'=>'tabs000.online', 'q'=>'q'),
	array('u'=>'easydialsearch.com', 'q'=>'q'),
	array('u'=>'pagina-deinicio.com', 'q'=>'q'),
	array('u'=>'sosodesktop.com', 'q'=>'q'),
	array('u'=>'uninstallmaster.com', 'q'=>'q'),
	array('u'=>'mplore.com', 'q'=>'q'),
	array('u'=>'searchturbo.com', 'q'=>'q'),
	array('u'=>'fvpimageviewer.com/search/', 'q'=>'q'),
	array('u'=>'tcl.start.fyi', 'q'=>'q'),
	array('u'=>'when.com', 'q'=>'q'),
	array('u'=>'esmuy.mx', 'q'=>'query'),
	array('u'=>'search.myway.com', 'q'=>'searchfor'),
	array('u'=>'search.goo.ne.jp', 'q'=>'MT'),
	array('u'=>'esmuy.be', 'q'=>'query'),
	array('u'=>'palikan.com', 'q'=>'q'),
	array('u'=>'searchlock.com', 'q'=>'q'),
	array('u'=>'portalne.ws', 'q'=>'q'),
	array('u'=>'kadaza.', 'q'=>'q'),
	array('u'=>'searchthe.website', 'q'=>'q'),
	array('u'=>'enhanced-search.', 'q'=>'q'),
	array('u'=>'search.navegaki.com', 'q'=>'searchfor'),
	array('u'=>'search.socialdownloadr.com', 'q'=>'q'),
	array('u'=>'search.orbitum.com', 'q'=>'search'),
	array('u'=>'search.sidecubes.com', 'q'=>'q'),
	array('u'=>'blackle.com', 'q'=>'q'),
	array('u'=>'beaucoup.com', 'q'=>'q'),
	array('u'=>'searchpaw.com', 'q'=>'q'),
	array('u'=>'technotop.xyz', 'q'=>'q'),
	array('u'=>'thesmartsearch.net', 'q'=>'q'),
	array('u'=>'airfind.com', 'q'=>'search_term'),
	array('u'=>'toshiba.com', 'q'=>'q'),
	array('u'=>'apps-search.com', 'q'=>'q'),
	array('u'=>'ozipcompression.com', 'q'=>'q'),
	array('u'=>'lifewireless.mobi', 'q'=>'search_term'),
	array('u'=>'internetportalne.ws', 'q'=>'q'),
	array('u'=>'searchprivacy.co', 'q'=>'q'),
	array('u'=>'searchthis.com', 'q'=>'q'),
	array('u'=>'searchalot.com', 'q'=>'q'),
	array('u'=>'hypersonica.com', 'q'=>'q'),
	array('u'=>'esmuy.fr', 'q'=>'query'),
	array('u'=>'mystart.space', 'q'=>'query'),
	array('u'=>'billigere.eu', 'q'=>'q'),
	array('u'=>'sogou.com', 'q'=>'query'),
	array('u'=>'kidzsearch.com', 'q'=>'q'),
	array('u'=>'appspot.com', 'q'=>'q'),
	array('u'=>'fiostrending.verizon.com', 'q'=>'q'),
	array('u'=>'sp-web.search.auone.jp', 'q'=>'q'),
	array('u'=>'zdsearch.com', 'q'=>'sbq'),
	array('u'=>'searchall.com', 'q'=>'q'),
	array('u'=>'centurylink.net', 'q'=>'q'),
	array('u'=>'kidrex.org', 'q'=>'q'),
	array('u'=>'searchguide.windstream.net', 'q'=>'q'),
	array('u'=>'m-search.co.uk', 'q'=>'schInput'),
	array('u'=>'portal.tds.net', 'q'=>'q'),
	array('u'=>'websearchne.ws', 'q'=>'q'),
	array('u'=>'izito.com', 'q'=>'q'),
	array('u'=>'izito.us', 'q'=>'q'),
	array('u'=>'midco.net', 'q'=>'q'),
	array('u'=>'att.net', 'q'=>'q'),
	array('u'=>'zapmeta.ws', 'q'=>'q'),
	array('u'=>'search.smt.docomo.ne.jp', 'q'=>'MT'),
	array('u'=>'icafemanager.com', 'q'=>'q'),
	array('u'=>'dudley.libnet.info', 'q'=>'q'),
	array('u'=>'wowway.net', 'q'=>'q'),
	array('u'=>'start.iminent.com', 'q'=>'q'),
	array('u'=>'virginmedia.com', 'q'=>'q'),
	array('u'=>'internet-start.net', 'q'=>'q'),
	array('u'=>'nintendo.co.jp', 'q'=>'p'),
	array('u'=>'queens.libnet.info', 'q'=>'q'),
	array('u'=>'shinysearch.com', 'q'=>'q'),
	array('u'=>'informationvine.com', 'q'=>'q'),
	array('u'=>'startpagina.nl', 'q'=>'query'),
	array('u'=>'laban.vn', 'q'=>'q'),
	array('u'=>'mytelus.telus.ca', 'q'=>'q'),
	array('u'=>'de.dolphin.com', 'q'=>'q'),
	array('u'=>'frontpage.pch.com', 'q'=>'q'),
	array('u'=>'virginmedia.com', 'q'=>'q'),
	array('u'=>'cox.com', 'q'=>'term'),
	array('u'=>'safesearchkids.com', 'q'=>'q'),
	array('u'=>'search.aol.co.uk', 'q'=>'q'),
	array('u'=>'surreylibraries.libnet.info', 'q'=>'q'),
	array('u'=>'nigma.ru', 'q'=>'s'),
	array('u'=>'intoautos.com', 'q'=>'q'),
	array('u'=>'telstra.com.au', 'q'=>'find'),
	array('u'=>'search.f-secure.com', 'q'=>'query'),
	array('u'=>'finderoo.com', 'q'=>'q'),
	array('u'=>'alothome.com', 'q'=>'slk'),
	array('u'=>'avira.net', 'q'=>'q'),
	array('u'=>'searchguide.level3.com', 'q'=>'q'),
	array('u'=>'mediacomcable.com', 'q'=>'q'),
	array('u'=>'windstream.net', 'q'=>'q'),
	array('u'=>'insppartner.com', 'q'=>'q'),
	array('u'=>'three.co.uk', 'q'=>'q'),
	array('u'=>'yippy.com', 'q'=>'query'),
	array('u'=>'armstrongmywire.com', 'q'=>'q'),
	array('u'=>'myfast-search.com', 'q'=>'q'),
	array('u'=>'coccoc.com', 'q'=>'query'),
	array('u'=>'atlanticbb.net', 'q'=>'q'),
	array('u'=>'symbaloo.com', 'q'=>'q'),
	array('u'=>'cincinnatibell.net', 'q'=>'q'),
	array('u'=>'refseek.com', 'q'=>'q'),
	array('u'=>'mediacomtoday.com', 'q'=>'q'),
	array('u'=>'uscellular.com', 'q'=>'q'),
	array('u'=>'fenrir-inc.com', 'q'=>'q'),
	array('u'=>'fulltabsearch.com', 'q'=>'q'),
	array('u'=>'easysearch.org.uk', 'q'=>'s'),
	array('u'=>'scienceforums.com', 'q'=>'q'),
	array('u'=>'yasp.no', 'q'=>'q'),
	array('u'=>'zapmeta.co.uk', 'q'=>'query'),
	array('u'=>'pancafepro.com', 'q'=>'q'),
	array('u'=>'zeelandnet.nl', 'q'=>'q'),
	array('u'=>'findblogs.com', 'q'=>'q'),
	array('u'=>'billigpris.eu', 'q'=>'q'),
	array('u'=>'shawconnect.ca', 'q'=>'q'),
	array('u'=>'startjuno.com', 'q'=>'q'),
	array('u'=>'goodskins.com', 'q'=>'q'),
	array('u'=>'zapmeta.com', 'q'=>'q'),
	array('u'=>'ok.hu', 'q'=>'q'),
	array('u'=>'emailaccountlogin.co', 'q'=>'search'),
	array('u'=>'faltradforum.de', 'q'=>'keywords'),
	array('u'=>'shopalike.dk', 'q'=>'k'),
	array('u'=>'izito.dk', 'q'=>'q'),
	array('u'=>'izito.info', 'q'=>'query'),
	array('u'=>'vosteran.com', 'q'=>'q'),
	array('u'=>'trezec.com', 'q'=>'search'),
	array('u'=>'findarticles.com', 'q'=>'sbq'),
	array('u'=>'straighttalk.com', 'q'=>'search_term'),
	array('u'=>'rakuten.co.jp', 'q'=>'qt'),
	array('u'=>'searchassist.verizon.com', 'q'=>'SearchQuery'),
	array('u'=>'yoursearch.me', 'q'=>'q'),
	array('u'=>'savevy.com', 'q'=>'q'),
	array('u'=>'epicsearch.in', 'q'=>'q'),
	array('u'=>'googsearch.us', 'q'=>'q'),
	array('u'=>'protectedio.com', 'q'=>'q'),
	array('u'=>'sendearnings.com', 'q'=>'query'),
	array('u'=>'youtube.com', 'q'=>'search_query'),
	array('u'=>'epicsearch.in', 'q'=>'q'),
	array('u'=>'finder.cox.net', 'q'=>'SearchQuery'),
	array('u'=>'search.frontier.com', 'q'=>'q'),
	array('u'=>'search.protectedio.com', 'q'=>'q'),
	array('u'=>'search.lilo.org', 'q'=>'q'),
	array('u'=>'findarticles.com', 'q'=>'sbq'),
	array('u'=>'sm.de', 'q'=>'q'),
	array('u'=>'kkmfind.com', 'q'=>'q'),
	array('u'=>'reference.com', 'q'=>'q'),
	array('u'=>'slickdeals.net', 'q'=>'q'),
	array('u'=>'.so.com', 'q'=>'q'),
	array('u'=>'only-search.com', 'q'=>'q'),
	array('u'=>'luxurycarsforfamily.com', 'q'=>'q'),
	array('u'=>'images.rambler.ru', 'q'=>'query'),
	array('u'=>'forum.slowtwitch.com', 'q'=>'search_string'),
	array('u'=>'internet.tre.it', 'q'=>'q'),
	array('u'=>'zapmeta.it', 'q'=>'q'),
	array('u'=>'search.fdownloadr.com', 'q'=>'q'),
	array('u'=>'search.findeer.com', 'q'=>'q'),
	array('u'=>'www.izito.it', 'q'=>'query'),
	array('u'=>'myepb.net', 'q'=>'q'),
	array('u'=>'botw.org', 'q'=>'SearchTerm'),
	array('u'=>'lukol.com', 'q'=>'q'),
	array('u'=>'dregol.com', 'q'=>'q'),
	// 3.0.7
	array('u'=>'topfastsearch.com', 'q'=>'q'),
	array('u'=>'ampxsearch.com', 'q'=>'s'),
	array('u'=>'goodthingsearch.com', 'q'=>'q'),
	array('u'=>'automaticfind.com', 'q'=>'q'),
	array('u'=>'top5find.com', 'q'=>'q'),
	array('u'=>'suggestionsearch.com', 'q'=>'q'),
	array('u'=>'junosearch.net', 'q'=>'q'),
	// 3.0.11
	array('u'=>'pacificair.com', 'q'=>'q'),
	array('u'=>'qgsearch.us', 'q'=>'q'),
	// 3.0.13 introducing regex match
	array('u'=>'.universiada.eu', 'm' => '|.universiada.eu/keyword/(.*)|i'),
	array('u'=>'search.xfinity.com', 'm' => '|search.xfinity.com/#web/(.*)/1|i'),
	array('u'=>'search.twcc.com', 'm' => '|search.twcc.com/#web/(.*)/1|i'),
	array('u'=>'pinterest.de/search', 'q'=>'q'),
	array('u'=>'search.zum.com', 'q'=>'query'),
	array('u'=>'szukaj.onet.pl', 'q'=>'qt'),
	array('u'=>'.easybib.com/cite/results', 'q'=>'query'),
	// 3.1.6
	array('u'=>'www.hellosearch.', 'q'=>'q'),
	array('u'=>'gaasearch.us', 'q'=>'q'),
	array('u'=>'trendtosearch.com', 'q'=>'q'),
	array('u'=>'bestfindthing.info', 'q'=>'q'),
	array('u'=>'search.1and1.com', 'q'=>'q'),
	array('u'=>'rockettab.com', 'q'=>'kwd'),
	array('u'=>'wikispaces.com', 'm' => '|.wikispaces.com/(.*)|i'),
	array('u'=>'amazon.it', 'q'=>'keywords'),
	array('u'=>'ya.ru', 'q'=>'q'),
	// 3.2.2
	array('u'=>'lonesearch.com', 'q'=>'q'),
	array('u'=>'evanscycles.com', 'q'=>'esvq'),
	// 3.2.4
	array('u'=>'krak.dk', 'm' => '|.krak.dk/(.*)/s%c3%b8g.cs|i'),
	// 3.2.7
	array('u'=>'bikeradar.com', 'q' => 'searchterm'),
	array('u'=>'zapmeta.es', 'q' => 'q'),
	// 3.2.13
	array('u'=>'shotdeadinthehead.com', 'q' => 'keywords'),
	// 3.3
	array('u'=>'lazta.com', 'q' => 'q'),
	array('u'=>'weloveshopping.com', 'q' => 'q'),
	array('u'=>'roomba-search.com', 'q' => 'query'),
	array('u'=>'excite.co.uk', 'q' => 'q'),
	array('u'=>'yangniao.net', 'q' => 'srchtxt'),
	array('u'=>'bildungsservice.lesestoff.ch', 'q' => 'bpmquery'),
	// 3.3.3
	array('u'=>'mencap.org.uk', 'q' => 'q'),
	array('u'=>'gopher.com', 'q' => 'q'),
	array('u'=>'search.totalav.com', 'q' => 'q'),
	array('u'=>'netdeals.com', 'q' => 'q'),
	array('u'=>'omigosearch.club', 'q' => 'q'),
	array('u'=>'unitsearch.club', 'q' => 'q'),
	array('u'=>'search.handy-tab.com', 'q' => 'q'),
	// 3.3.5
	array('u'=>'www.linkedin.com/search/results/', 'q' => 'keywords'),
	array('u'=>'suche.gmx.net', 'q' => 'q'),
	array('u'=>'.search.com', 'q' => 'q'),
	array('u'=>'search.selfbutler.com', 'q' => 'utm_term'),
	array('u'=>'.searchnow.com', 'q' => 'q'),
	array('u'=>'.coinup.org', 'q' => 'q'),
	array('u'=>'www.izito.', 'q' => 'q'),
	array('u'=>'smarter.com', 'q' => 'q'),
	array('u'=>'zapmeta.uk', 'q' => 'q'),
	// 3.3.7
	array('u'=>'comparing.xyz', 'q' => 'q'),
	array('u'=>'www.krak.dk', 'q' => 'search_word'),
	// 3.3.9
	array('u'=>'.seekkees.com', 'q' => 'q'),
	// 3.3.14
	array('u'=>'search.uselilo.org', 'q' => 'q'),
	array('u'=>'cableone.net', 'q' => 'q'),
	array('u'=>'juniorsafesearch.com', 'q' => 'q'),
	// 3.3.17
	array('u'=>'linksdk.dk', 'q' => 'phrase'),
	array('u'=>'dspace.bcucluj.ro', 'q' => 'filterquery'),
	// 3.3.18
	array('u'=>'app.buzzsumo.com', 'q' => 'q'),
	array('u'=>'amino.dk/search/searchresults.aspx', 'q' => 'q'),
	array('u'=>'app.kwfinder.com', 'q' => 'keyword'),
	// 3.3.21
	array('u'=>'www.eniro.se', 'q' => 'search_word'),
	array('u'=>'search.clearch.org', 'q' => 'q'),
	// 3.3.23
	array('u'=>'elatar.com', 'q' => 'q'),
	// 3.3.29
	array('u'=>'freaktab.com/search', 'q' => 'q'),
	array('u'=>'idb.buzzstream.com', 'q' => 'q'),
	array('u'=>'yandex.com.tr/search/', 'q' => 'text'),
	array('u'=>'search.xfinity.com', 'q' => 'searchterm'),
	array('u'=>'inboxdollars.com', 'q' => 'query'),
	array('u'=>'quafind.com', 'q' => 'q'),
	array('u'=>'privatebrowsing.com', 'q' => 'q'),
	array('u'=>'navigationshilfe.t-online.de', 'q' => 'q'),
	array('u'=>'nav-goo.com', 'q' => 'q'),
	array('u'=>'searx.dk', 'q' => 'q'),
	array('u'=>'.xfinity.com', 'q' => 'searchterm'),
	array('u'=>'ordissinaute.fr', 'q' => 'q'),
	array('u'=>'elatar.com', 'q' => 'q'),
	array('u'=>'suddenlink.net', 'q' => 'q'),
	array('u'=>'atzu.org', 'q' => 'q'),
	array('u'=>'zapmetasearch.com', 'q' => 'q'),
	// 3.3.30
	array('u'=>'search-story.com', 'q' => 'q'),
	array('u'=>'gibiru.com', 'q' => 'q'),
	// 3.3.31
	array('u'=>'jobindex.dk', 'q' => 'q'),
	array('u'=>'overdrive.com', 'q' => 'q'),
	array('u'=>'kysy.com', 'q' => 'q'),
	// 3.3.32
	array('u'=>'froogle.ihyd.com', 'q' => 'q'),
	array('u'=>'.wibki.com', 'q' => 'q'),




	/*



http://www.infobel.com/da/denmark/search/businessresults?token=eyjddxjyzw50ugfnzsi6mswiumvjb3jkc1blclbhz2uiojasiknvdw50cnldb2rlijpudwxslcjcdxnpbmvzc1r5cguiojesilnlyxjjafrlcm0ioijyawdodcbwzw9wbguilcjtzwfyy2hmb2nhdglvbii6bnvsbcwiumvzawrlbnrpywxtzwfyy2huzxjtijpudwxslcjtzwfyy2hdyxrlz29yawvzijpudwxslcjdyxrlz29yeunvzguiom51bgwsiknhdgvnb3j5tgv2zwwiojasiklztwv0ysi6zmfsc2usikxhdgl0dwrlijpudwxslcjmb25naxr1zguiom51bgwsik9yzgvymdgiom51bgwsik9yzgvymdkiom51bgwsik5lyxjcesi6bnvsbcwiu3ryawn0tg9jyxrpb24iomzhbhnllcjdyxrlz29yevnlyxjjaci6zmfsc2usilrvcenpdgllc051bwjlcii6mcwivg9wq2l0awvzqxjlysi6mcwivg9wq2f0zwdvcmllc051bwjlcii6mcwivg9wq29tcgv0axrvcnnodw1izxiiojasilrvcenvbxbldgl0b3jzqxjlysi6mcwivmfsawrgb3jfbmnyexb0aw9uijpmywxzzx0=














IGNORE:

https://www.linkedin.com/messaging/*
FROM https://www.linkedin.com/messaging/thread/6367371086828576768/

+ https://app.accuranker.com/keywords/list/workingmediadk/fyuncedk-2/





		https://twitter.com/search?q=place%3a07d9d73a1ac88000

		https://vancouver.ca/map.aspx?q=453+west+12th+ave,+vancouver,+bc+v5k+1v4,+canada
		*/

	array('u'=>'yellowpages.com', 'q'=>'search_terms')
); // FINAL ONE - no comma :-)
?>